/**
 * A fence language's display name: the label a code block's header shows in
 * place of its language id, and the tab label of an untitled block in a
 * `<CodeGroup>`. Shared by the docs layout's script and the tabs element's,
 * so a block reads the same in both places.
 */

/** Language id (lowercase, aliases included) → display name. */
const LANGUAGE_LABELS: ReadonlyMap<string, string> = new Map([
  ["astro", "Astro"],
  ["bash", "Bash"],
  ["c", "C"],
  ["c#", "C#"],
  ["c++", "C++"],
  ["console", "Console"],
  ["cpp", "C++"],
  ["cs", "C#"],
  ["csharp", "C#"],
  ["css", "CSS"],
  ["dart", "Dart"],
  ["diff", "Diff"],
  ["docker", "Dockerfile"],
  ["dockerfile", "Dockerfile"],
  ["elixir", "Elixir"],
  ["go", "Go"],
  ["gql", "GraphQL"],
  ["graphql", "GraphQL"],
  ["html", "HTML"],
  ["http", "HTTP"],
  ["java", "Java"],
  ["javascript", "JavaScript"],
  ["js", "JavaScript"],
  ["json", "JSON"],
  ["jsonc", "JSONC"],
  ["jsx", "JSX"],
  ["kotlin", "Kotlin"],
  ["kt", "Kotlin"],
  ["lua", "Lua"],
  ["markdown", "Markdown"],
  ["md", "Markdown"],
  ["mdx", "MDX"],
  ["php", "PHP"],
  ["plaintext", "Text"],
  ["powershell", "PowerShell"],
  ["ps1", "PowerShell"],
  ["py", "Python"],
  ["python", "Python"],
  ["rb", "Ruby"],
  ["rs", "Rust"],
  ["ruby", "Ruby"],
  ["rust", "Rust"],
  ["scala", "Scala"],
  ["scss", "SCSS"],
  ["sh", "Shell"],
  ["shell", "Shell"],
  ["shellsession", "Shell Session"],
  ["sql", "SQL"],
  ["svelte", "Svelte"],
  ["swift", "Swift"],
  ["text", "Text"],
  ["toml", "TOML"],
  ["ts", "TypeScript"],
  ["tsx", "TSX"],
  ["txt", "Text"],
  ["typescript", "TypeScript"],
  ["vue", "Vue"],
  ["xml", "XML"],
  ["yaml", "YAML"],
  ["yml", "YAML"],
  ["zsh", "Zsh"],
]);

/** The display name of a fence language, or the id as written for one without a name here. */
export const languageLabel = (language: string): string =>
  LANGUAGE_LABELS.get(language.toLowerCase()) ?? language;
